CREATE TABLE AUCTION (
    AUCTION_NO NUMBER NOT NULL,
    AUCTION_SCHEDULE_NO NUMBER NOT NULL,
    WORK_NO NUMBER NOT NULL,
    AUCTION_SUCCESS_BIDDER VARCHAR2(20) NOT NULL,
    AUCTION_LOT NUMBER DEFAULT 9999 NOT NULL,
    AUCTION_LOW_PRICE NUMBER NULL,
    AUCTION_HIGH_PRICE NUMBER NULL,
    AUCTION_START_DATE TIMESTAMP NULL,
    AUCTION_END_DATE TIMESTAMP NULL,
    AUCTION_STATE VARCHAR2(21) NULL,
    AUCTION_HAMMER_PRICE NUMBER NULL,
    AUCTION_PURCHASE_PRICE NUMBER NULL,
    AUCTION_CONSIGNER VARCHAR2(21) NULL,
    AUCTION_CONSIGNMENT_FEE NUMBER NULL,
    AUCTION_NET_PROCEEDS NUMBER DEFAULT 0 NOT NULL ,
    AUCTION_BID_INCREMENT NUMBER DEFAULT 20000 NOT NULL
);
